<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\StillHere.Application\StillHere.Application.csproj" />
    <ProjectReference Include="..\StillHere.Infrastructure\StillHere.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="SyntaxCircus.AspNetCore.Serilog" />
    <PackageReference Include="SyntaxCircus.Blazor.Components" />
    <PackageReference Include="SyntaxCircus.Common" />
    <PackageReference Include="SyntaxCircus.DotEnv" />
  </ItemGroup>

  <PropertyGroup>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

</Project>
