<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\StillHere.Application\StillHere.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="SyntaxCircus.Http.Resilience" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="StillHere.Infrastructure.Tests" />
  </ItemGroup>

</Project>
