// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StillHere.Infrastructure.Persistence;

#nullable disable

namespace StillHere.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("StillHere.Infrastructure.Persistence.Entities.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AdminUsers");
                });

            modelBuilder.Entity("StillHere.Infrastructure.Persistence.Entities.AuditLogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ManagedDomainId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NewIp")
                        .HasColumnType("TEXT");

                    b.Property<string>("OldIp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ManagedDomainId");

                    b.ToTable("AuditLogEntries");
                });

            modelBuilder.Entity("StillHere.Infrastructure.Persistence.Entities.DnsProviderCredential", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptedSecrets")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DnsProviderCredentials");
                });

            modelBuilder.Entity("StillHere.Infrastructure.Persistence.Entities.GlobalSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AuditLogRetentionDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultPollingIntervalSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalIpCheckServices")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IpDetectionMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GlobalSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DefaultPollingIntervalSeconds = 300,
                            ExternalIpCheckServices = "[\"https://ifconfig.me/ip\",\"https://api.ipify.org\",\"https://icanhazip.com\"]",
                            IpDetectionMode = "ExternalAndProviderReported"
                        });
                });

            modelBuilder.Entity("StillHere.Infrastructure.Persistence.Entities.ManagedDomain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DomainName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastCheckedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastKnownIp")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PollingIntervalOverrideSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProviderCredentialId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProviderCredentialId");

                    b.ToTable("ManagedDomains");
                });

            modelBuilder.Entity("StillHere.Infrastructure.Persistence.Entities.NotificationChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BodyTemplate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EncryptedPassword")
                        .HasColumnType("TEXT");

                    b.Property<string>("FromAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("HttpMethod")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SmtpHost")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SmtpPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ToAddresses")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TriggerOnFailure")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TriggerOnIpChange")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TriggerOnSuccess")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseSsl")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NotificationChannels");
                });

            modelBuilder.Entity("StillHere.Infrastructure.Persistence.Entities.AuditLogEntry", b =>
                {
                    b.HasOne("StillHere.Infrastructure.Persistence.Entities.ManagedDomain", "ManagedDomain")
                        .WithMany()
                        .HasForeignKey("ManagedDomainId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ManagedDomain");
                });

            modelBuilder.Entity("StillHere.Infrastructure.Persistence.Entities.ManagedDomain", b =>
                {
                    b.HasOne("StillHere.Infrastructure.Persistence.Entities.DnsProviderCredential", "ProviderCredential")
                        .WithMany("ManagedDomains")
                        .HasForeignKey("ProviderCredentialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProviderCredential");
                });

            modelBuilder.Entity("StillHere.Infrastructure.Persistence.Entities.DnsProviderCredential", b =>
                {
                    b.Navigation("ManagedDomains");
                });
#pragma warning restore 612, 618
        }
    }
}
